version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 99
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    assignees:
      - "biow0lf"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 99
    assignees:
      - "biow0lf"

  - package-ecosystem: docker
    directory: /OLD
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /OLD
    schedule:
      interval: daily
